### ISSUE TITLE
Body does not appear to be passing through to the endpoint

### ISSUE THREAD

**Issue by jcohen-hdb** [Ethan-Arrowood/undici-fetch#67]
I'm seeing an issue where I provide a body in the Request, but it does not appear to pass through to the endpoint. In my case, I'm working with HarperDB as the endpoint, so you can see my example code here. HarperDB responds with `{error: "Body cannot be empty when content-type is set to 'application/json'"}`, which leads me to believe there's an issue passing the body in the request. 

```
const fetch = require('undici-fetch')
const { Request } = require('undici-fetch')
const request = new Request('http://localhost:9925', {
    method: 'POST',
    headers: {
        "authorization": "Basic AUTH_TOKEN",
        "content-type": "application/json"
    },
    body: JSON.stringify({
        "operation": "sql",
        "sql": "SELECT * FROM dev.dog"
    })
})
fetch(request)
    .then(res => res.json())
    .then(json => console.log(json))
```

**Comment by Ethan-Arrowood** [comment]
https://github.com/Ethan-Arrowood/undici-fetch/blob/007f429032e08d3ecd7d695e35f1fa89e07197ee/src/request.js#L49

This is an issue because undici-fetch is currently not integrated with the experimental [WebStreams](https://nodejs.org/api/webstreams.html) api. Once it is I believe this will be fixed. For now I'd recommend not instantiating your own Request instance, but instead passing everything to the `fetch` function itself.

**Comment by Ethan-Arrowood** [comment]
undici-fetch is now apart of [undici](https://github.com/nodejs/undici) core 🚀 as a result this repo is being archived and all current PRs and issues are being closed out. 

Check out the [undici 4.4.1](https://github.com/nodejs/undici/releases/tag/v4.4.1) for the latest fetch API
